version: '3.8'

services:
  web:
    build: .
    container_name: iran_web
    ports:
    - "8080:80"
    volumes:
      - ./web:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    container_name: iran_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iran_news
      MYSQL_USER: user
      MYSQL_PASSWORD: 
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: